from __future__ import annotations

from pathlib import Path

from scripts.check_no_dev_secrets import DEV_SECRET_PATTERNS
from scripts.generate_secrets import build_secret_bundle, render_env


def test_generate_secrets_returns_expected_keys() -> None:
    secret_bundle = build_secret_bundle()

    assert secret_bundle["JWT_SECRET_KEY"]
    assert secret_bundle["KILLSWITCH_SECRET"]
    assert secret_bundle["AUDIT_SIGNING_SECRET"]
    assert secret_bundle["OPERATOR_SESSION_SECRET"]
    assert secret_bundle["EXECUTOR_HMAC_SECRET"]
    assert "platform-admin" in secret_bundle["OPERATOR_API_KEYS_JSON"]


def test_render_env_formats_key_value_output() -> None:
    output = render_env({"JWT_SECRET_KEY": "abc123", "KILLSWITCH_SECRET": "def456"})

    assert output.startswith("# Generated by scripts/generate_secrets.py")
    assert "JWT_SECRET_KEY=abc123" in output
    assert "KILLSWITCH_SECRET=def456" in output


def test_production_template_contains_no_dev_secret_patterns() -> None:
    template = Path(".env.production.example").read_text(encoding="utf-8")

    for pattern in DEV_SECRET_PATTERNS:
        assert pattern not in template
