#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import secrets


def _token_hex(byte_length: int = 32) -> str:
    return secrets.token_hex(byte_length)


def build_secret_bundle() -> dict[str, str]:
    operator_api_key = f"op_{secrets.token_urlsafe(32)}"
    service_operator_api_key = f"svc_{secrets.token_urlsafe(32)}"
    return {
        "JWT_SECRET_KEY": _token_hex(),
        "KILLSWITCH_SECRET": _token_hex(),
        "AUDIT_SIGNING_SECRET": _token_hex(),
        "OPERATOR_SESSION_SECRET": _token_hex(),
        "WEBHOOK_HMAC_SECRET": _token_hex(),
        "EXECUTOR_HMAC_SECRET": _token_hex(),
        "EXECUTOR_CREDENTIAL_SECRET": _token_hex(),
        "POSTGRES_PASSWORD": _token_hex(24),
        "OPERATOR_API_KEYS_JSON": json.dumps(
            {
                operator_api_key: {
                    "subject": "platform-admin",
                    "roles": [
                        "agent_admin",
                        "approver",
                        "security_admin",
                        "auditor",
                        "killswitch_operator",
                    ],
                }
            },
            separators=(",", ":"),
        ),
        "SERVICE_OPERATOR_API_KEY": service_operator_api_key,
    }


def render_env(secrets_map: dict[str, str]) -> str:
    lines = [
        "# Generated by scripts/generate_secrets.py",
        "# Review before use and store in your secret manager.",
    ]
    for key, value in secrets_map.items():
        lines.append(f"{key}={value}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate strong secrets for ACR production deployments.")
    parser.add_argument(
        "--format",
        choices=("env", "json"),
        default="env",
        help="Output format.",
    )
    args = parser.parse_args()

    secrets_map = build_secret_bundle()
    if args.format == "json":
        print(json.dumps(secrets_map, indent=2, sort_keys=True))
        return
    print(render_env(secrets_map), end="")


if __name__ == "__main__":
    main()
